# coding: utf-8

"""
    Supplyframe API

    <h2>Supplyframe API Gateway</h2>  Collection of Supplyframe endpoints exposed through the Supplyframe API Gateway.  <h3>Authorization</h3>  All requests should be authorized with parameter \"token\" set to value provided by Supplyframe. In addition to \"token,\" for routes that are intended to be used by end-user applications, parameter \"uuid\" is required. \"uuid\" should represent a unique identifier of the end-user. It can be generated as a random string that's unique for the duration of the user session, and should not contain any PII information.  <h3>Response</h3>  Response is a JSON object. Response should not be consumed if the status code has a value other than 200.  <h3>Status codes returned by API</h3>  <table>     <tr>         <td>200</td>         <td>valid response, consume body</td>     </tr>     <tr>         <td>400</td>         <td>bad request</td>     </tr>     <tr>         <td>401</td>         <td>unauthorized request</td>     </tr>     <tr>         <td>404</td>         <td>route does not exist</td>     </tr>     <tr>         <td>429</td>         <td>too many requests. Rate limiting is based on token and uuid provided</td>     </tr>     <tr>         <td>500</td>         <td>internal server error</td>     </tr> </table>  <h3>Versioning</h3>  API is versioned. Each route has it's own version counting. For each change in API response, new parameter supported, fields added or removed new version will be released.   # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]
    

setup(
    name=NAME,
    version=VERSION,
    description="Supplyframe API",
    author_email="",
    url="",
    keywords=["Swagger", "Supplyframe API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    &lt;h2&gt;Supplyframe API Gateway&lt;/h2&gt;  Collection of Supplyframe endpoints exposed through the Supplyframe API Gateway.  &lt;h3&gt;Authorization&lt;/h3&gt;  All requests should be authorized with parameter \&quot;token\&quot; set to value provided by Supplyframe. In addition to \&quot;token,\&quot; for routes that are intended to be used by end-user applications, parameter \&quot;uuid\&quot; is required. \&quot;uuid\&quot; should represent a unique identifier of the end-user. It can be generated as a random string that&#39;s unique for the duration of the user session, and should not contain any PII information.  &lt;h3&gt;Response&lt;/h3&gt;  Response is a JSON object. Response should not be consumed if the status code has a value other than 200.  &lt;h3&gt;Status codes returned by API&lt;/h3&gt;  &lt;table&gt;     &lt;tr&gt;         &lt;td&gt;200&lt;/td&gt;         &lt;td&gt;valid response, consume body&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;         &lt;td&gt;400&lt;/td&gt;         &lt;td&gt;bad request&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;         &lt;td&gt;401&lt;/td&gt;         &lt;td&gt;unauthorized request&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;         &lt;td&gt;404&lt;/td&gt;         &lt;td&gt;route does not exist&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;         &lt;td&gt;429&lt;/td&gt;         &lt;td&gt;too many requests. Rate limiting is based on token and uuid provided&lt;/td&gt;     &lt;/tr&gt;     &lt;tr&gt;         &lt;td&gt;500&lt;/td&gt;         &lt;td&gt;internal server error&lt;/td&gt;     &lt;/tr&gt; &lt;/table&gt;  &lt;h3&gt;Versioning&lt;/h3&gt;  API is versioned. Each route has it&#39;s own version counting. For each change in API response, new parameter supported, fields added or removed new version will be released.   # noqa: E501
    """
)
